name: organoid-programming
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - jupyterlab>=4.0
  - notebook>=7.0
  - ipykernel>=6.0
  - numpy>=1.26
  - pandas>=2.1
  - matplotlib>=3.8
  - h5py>=3.10
  - pytest>=8.0
  - pytest-mock>=3.12
  - pip:
      - cl-sdk
      - python-dotenv>=1.0.0
      - rich>=13.0.0
